name: PerfectTags
version: '1.0-SNAPSHOT'
main: org.aneras.mc.perfecttags.PerfectTags
api-version: 1.18
depend: [ PlaceholderAPI ]
authors: [ Aneras ]
softdepend:
  - LuckPerms
commands:
  tags:
    usage: /tags
